import csv
from collections import defaultdict
import ast

keyword_groups = {
    "Natural Language Processing": [
        "Grammar", "Dictionaries", "Decision making", "Decoding", "Error analysis", "Encoding", "Knowledge based systems", 
        "Knowledge discovery", "Knowledge engineering", "Knowledge transfer", "Labeling", "Learning (artificial intelligence)", 
        "Learning systems", "Text-to-image synthesis", "Natural language processing", "Natural languages", "Linguistics", "Message passing", "Inference algorithms", 
        "Markov processes", "Markov random fields", "Mixture models", "Pragmatics", "Prediction algorithms", "Predictive models", "Probabilistic logic",
        "Semantics", "Search problems", "Sequential analysis", "Supervised learning", "Vocabulary", "Text recognition", "Syntactics", "Taxonomy",
        "Character recognition",
        "Context-aware services",
        "Handwriting recognition",
        "Optical character recognition software",
        "Phonetics",
        "Speech enhancement",
        "Speech recognition",
        "Twitter",
        "Voice activity detection", "Annotations",
        "Semantic search",
        "Sentiment analysis",
        "Text analysis",
        "Text categorization",
        "Writing", "Information filters",
        "Prediction methods", "Machine translation", "Vocabulary",
        "Text detection", "Tokenization", "Speech processing",
    ],
    "Medical Imaging and Healthcare": [ "Auditory system", "Embryo","Body regions", "Heart", "Human activity recognition",
        "Medical imaging", "Biomedical imaging", "Computed tomography", "Cancer", 
        "Genetic expression", "Biomedical optical imaging", "Disease diagnosis", "Blood vessels", "Bones",
        "Diseases", "Biomedical imaging", "Disease diagnosis", "X-ray imaging", "Lung", "Mice", 
        "Medical diagnostic imaging", "Magnetic resonance imaging", "Lesions", "Liver",
        "Positron emission tomography", "Pancreas", "Pathology", "Retina", "Medical diagnostic imaging",
        "Genomics", "Mel frequency cepstral coefficient", "Optical imaging", "Optical filters", 
        "Optical propagation", "Optical scattering", "Picture archiving and communication systems", "Prognostics and health management", "Assisted living",
        "Biomedical monitoring", "Biopsy", "Calcium", "Heart rate", "Hospitals", "Plethysmography", "Phantoms", "Thorax", "Teeth", "Veins", "X-rays",
        "Blindness","Autism", "Axons", "Colonoscopy", "Diabetic retinopathy", "Functional magnetic resonance imaging", 
        "Gait recognition", "Lung", "Lung cancer", "Medical diagnosis", "Neurological diseases", 
        "Pneumonia", "Surgery", "Telemedicine", "Visual impairment", "Magnetic devices",
        "Heart beat",
        "Hemorrhaging",
        "Pediatrics", "Tomography",
        "Radiometry",
        "X-ray scattering", "Microscopy",
        "Neural activity",
        "Neuroscience",
        "Fingerprint recognition",
        "Face detection",
        "Iris recognition", "COVID-19",
        "Histopathology",
        "Melanoma",
        "Medical services",
        "Myocardium",
        "Radiography",
        "Retinopathy",
        "Toxicology",
        "Wounds", "Iris",
        "MIMICs", "Dentistry", 
        "Photothermal effects",
        "Temperature distribution",
        "Thermal analysis",
        "Thermal lensing",
        "Thermal stresses", "Angiography", "Biology", "Cells (biology)", "Medical conditions", "Minimally invasive surgery", 
        "Photoplethysmography", "Physiology", "Radiology", "Retinal vessels", "Scanning electron microscopy", 
        "Fluorescence", "Ultrasonic imaging",  "Genetics", "Neuromorphics",
        "Proteins", "Pandemics", "Stereo image processing", "Bioinformatics", "Biological neural networks", 
        "Biological system modeling", "Cloning", "DNA", "Drugs", "Pulse measurements", "Punching", "Telemedicine", "Morphology",
        "Medical conditions",
        "Pneumonia",  "Neural implants", 
    ],
    "Autonomous Vehicles and Robotics": ["Autonomous aerial vehicles", "Human-robot interaction", "Vehicle detection",
        "Autonomous driving", "Autonomous automobiles", "Autonomous vehicles", 
        "Robotics", "Automation", "Aerospace electronics", "Path planning", 
        "SLAM", "Collision avoidance", "Navigation", "UAVs", "Drone vision", "Space vehicles",
        "Aerial vehicle navigation", "Remote inspections", 
        "Swarm intelligence", "Autonomous systems","Global Positioning System", "Wireless sensor networks",
        "Automobiles", "Autonomous vehicles", "Robotics", "Path planning", "Navigation", 
        "UAVs", "Drone vision", "Aerial vehicle navigation",
        "Engines", "Humanoid robots", "Marine vehicles", "Legged locomotion", "Manipulators",
        "Robot sensing systems", "Robot vision systems", "Robots", "Simultaneous localization and mapping", "Motion compensation", 
        "Motion estimation", "Object detection", "Object recognition", "Object segmentation", "Object tracking", 
        "Robot vision systems", "Unmanned aerial vehicles", "Vehicle dynamics", "Vehicles", "Visual odometry", "Visual perception", "Visual systems", "Autonomous robots",
        "Drones",
        "Helicopters",
        "Motorcycles",
        "Servosystems", "Aircraft",
        "Boats",
        "Lane detection",
        "Propulsion",
        "Robot kinematics",
        "Service robots",
        "Trajectory planning", "Machine vision",
        "Sensor fusion",
        "Traffic control",
        "Mobile robots", "Motion measurement", "Multisensory integration",
        "Calibration", "Azimuth", "Bars", "Dynamic range", "Dynamic scheduling", "Dynamics",
        "Detection algorithms", "Detectors", "Controllability", "Gyroscopes", "Bidirectional control",
        "Markov decision processes",
        "Greedy algorithms", 
        "Deformation", "Filters",
        "Clocks",  "Cloud computing", 
        "Handheld computers",  "Heating systems", 
        "Bicycles", "Binary codes", 
        "Colored noise",  "Computational efficiency", 
        "Degradation", "Delays", 
        "Dogs", "Cats", "Couplings", "Cows", "DSL", 
        "Space exploration", "Heating systems", "Fabrication",
        "Mobile handsets", 
        "Electroencephalography", "Electron tubes",
        "Explosives", "Deformable models", 
        "Glass", "Gold", "Graphite", "Gravity", 
        "Ink", "Ions", "Iron", "Jitter", "Hyperspectral imaging", 
        "Manganese", "Manuals", "Nickel", "Lattices", "Layout", 
        "Physics", "Planning", "Reliability", "Robustness",
        "Space heating", "Strain", "Spirals", "Switches",
        "Synchronization", "Tensile stress", 
        "Tuning", "Wiring", "Xenon", "Zinc", "Zirconium",
        "Optical fiber networks", "Optical network units", "Solid modeling", "Spatiotemporal phenomena",
        "Trajectory", "Fatigue", "Fault detection", "High dynamic range", "High-temperature superconductors",
        "Pedestrians",  "Lead acid batteries", "Logic programming", "Materials science and technology", 
        "Temperature measurement", "Velocity measurement", "Exploration", "Glass box", "Solids", "Floors",
        "Grippers", "Grounding", "Hafnium", "Fuses", "Gallium nitride",
        "Compounds", "Color", "Codecs", "Inductors", "Metals", "Oscilloscopes", "Impedance matching", 
        "Excavation", "Extraterrestrial phenomena", "Maintenance", "Memory", 
        "Earth Observing System", "Electronic publishing", "Portable computers", "Mobile applications",
        "System performance", "Satellite broadcasting", "Sensor systems", 
    ],
    "Human-Centric Vision": ["Usability", "Affordances", "Forehead", "Pain","Human computer interaction", "Human in the loop", "Oral communication", "Sign language",
        "Activity recognition", "Human pose estimation", "Gesture recognition", 
        "Facial recognition", "Emotion analysis", "Gait analysis", "Cognition", 
        "Assistive technology", "Creativity","Behavioral sciences", "Eyelids", "Fingers", "User experience", "User interfaces",
        "Emotion recognition", "Gesture recognition", "Facial recognition", "Cognition",
        "Face recognition", "Facial features", "Gaze tracking", "Face", "Facial recognition", "Head", "Lips",
        "Mouth", "Hip", "Neck", "Muscles", "Hippocampus", "Psychology", "Hair", "Microphones", "Nose",
        "Elbow", "Ear", "Skin", "Torso", "Wrist", "Face detection", "Foot", "Aging", "Footwear",
        "Fingerprint recognition", "Clothing", "Fabrics",
        "Iris recognition",
        "Identification of persons", "Biometrics (access control)",
        "Faces",
        "Facial animation",
        "Human factors",
        "Human image synthesis",
        "Tactile sensors", "Force",
        "Stress",
        "Weight measurement"
    ],
    "Natural Scenes and Environmental Analysis": ["Fluids", "Water", "Climate change", "Flora", "Flowering plants", "Geospatial analysis", "Land surface", "Phenology", "Plant diseases", 
        "Plantations",
        "Agriculture", "Atmospheric measurements", "Atmospheric modeling", 
        "Clouds", "Remote sensing", "Ocean monitoring", "Aerial imagery", 
        "Satellite images", "Climate analysis","Floods", "Sea surface",
        "Agriculture", "Atmospheric measurements", "Clouds", "Ocean monitoring", "Climate analysis",
        "Geophysical measurement techniques", "Ground penetrating radar", "Extraterrestrial measurements", "Meteorology",
        "Rain", "Rivers", "Snow", "Roads", "Public transportation", "Geophysical measurement techniques", 
        "Acoustics", "Animals", "Birds", "Clutter", "Liquids", "Monitoring", "Pipelines", "Powders", "Photonics",
        "Satellites", "Sensors", "Sensor arrays", "Spatial resolution", "Spatial coherence", 
        "Vegetation", "Urban areas", "Water resources", "Biodiversity",
        "Earth",
        "Environmental analysis",
        "Geology",
        "Natural scenes",
        "Sea measurements",
        "Vegetation mapping",
        "Wildlife", "Forestry",
        "Fungi",
        "Methane",
        "Rocks",
        "Whales",
        "Lightning", "Ecosystems","Light sources",
        "Horses",
        "Hurricanes",
        "Oceans",
        "Plants (biology)",
        "Reservoirs",
        "Spaceborne radar",  "Irrigation",
        "Systematics"
    ],
    "Augmented Reality (AR) and Virtual Reality (VR)": ["Blogs", "Headphones", "Keyboards", "Wheels",
        "Augmented reality", "Virtual reality", "3D reconstruction", 
        "Avatars", "Holography", "Immersive environments",
        "3D reconstruction", "Immersive environments",
        "Graphics", "Graphics processing units","Telepresence",
        "Rendering (computer graphics)", "Virtual reality", "3D reconstruction", "Immersive environments",
        "Three-dimensional displays", "Two dimensional displays", "Augmented reality",
        "Extended reality",
        "Immersive experience",
        "Mixed reality",
        "Virtual environments",
        "Virtual private networks",
        "X reality", "Animation",  "Image motion analysis",
        "Optical flow",
        "Radar imaging", "Visual effects", "Entertainment industry", 
    ],
    "Video Analysis and Action Recognition": ["Digital images", "Image forensics", "Sensor systems and applications", "Vision sensors",
        "Video processing", "Motion segmentation", "Event detection", 
        "Temporal analysis", "Video summarization", "Action recognition",
        "Motion segmentation", "Event detection", "Video summarization", "Action recognition",
        "Image recognition", "Image segmentation", "Image matching", "Image resolution", "Image retrieval", "Image restoration",
        "Motion pictures", "Pattern recognition", "Pose estimation", "Saliency detection", "Motion compensation", "Motion estimation",
        "Joints", "Junctions", "Kinematics", "Kinetic theory",  "Message passing", "Monitoring",
        "Structure from motion", "Streaming media",
        "Target recognition", "Target tracking", "Tracking", "Video surveillance", "Video sequences", "Videos", "Video compression", "Action recognition",
        "Motion capture",
        "Video coding","Instance segmentation",
        "Video description",
        "Video games", "Image sequences", "Stereo image processing",
        "Video on demand",
        "Video recording",
        "Video tracking", "Synthetic aperture radar",
        "Radar tracking",
        "Sonar detection", "Character generation",
        "Human image synthesis" , "Radar",
        "Firing",
        "Explosions", "Cameras", "Cams",  "DVD",
        "Photography", "Brightness", "Motion detection",
        "UHDTV", "TV", "Films", 
        "Teleconferencing", "Recording", "Gray-scale", 
    ],
    "Generative Models and Creativity": ["Multilayer perceptrons",
        "GANs", "Image generation", "Style transfer", "Artistic applications", 
        "Artificial intelligence", "Boosting", 
        "Brain modeling", "Artificial neural networks",
        "Art", "Boosting", "Artificial neural networks",
        "Generative adversarial networks", "Image generation", "Image representation",
        "Painting", "Paints", "Multimedia communication", "Art", "Generative adversarial networks", "Deepfakes",
        "Generative models",
        "Image synthesis","Federated learning", "Self-supervised learning", "Music",
        "Photorealism",
        "Representation learning", "Mashups",
        "Synthetic data",
        "Zero-shot learning", "Active appearance model",
        "Animation", "Collaborative work",  "Annealing",
    ],
    "Security and Surveillance": ["Access control", "Copyright protection", "Encryption", "Threat modeling",
        "Surveillance systems", "Anomaly detection", "Crowd monitoring", 
        "Camera networks", "License plate recognition", "Security applications", 
        "Alarm systems", "Broadcasting",
        "Surveillance systems", "Anomaly detection", "Camera networks", "License plate recognition", "Security applications",
        "Forensics", "Forgery", "Face recognition", "Image registration", "Image quality", "Image sensors",
        "Privacy", "Security", "Search engines", "Protocols", "Forensics", "Forgery", "Anomaly detection",
        "Surveillance", "Video surveillance", "Adversarial machine learning",
        "Authentication",
        "Cyber-physical systems",
        "Law enforcement",
        "Safety","Information filtering", "Information sharing", "Telecommunication traffic",
        "Security",
        "Surveillance", "Face detection",
        "Fingerprint recognition",
        "Iris recognition",
        "Synthetic aperture radar", "Radar detection",
        "Radar imaging",
        "Weapons", "Radar",
        "Splicing"
    ],
    "Scene Understanding and Reconstruction": ["Knowledge representation", "Inference mechanisms", "Visual analytics",
        "Scene segmentation", "Semantic segmentation", "Depth estimation", 
        "Scene parsing", "Clustering algorithms", "Clustering methods", 
        "Context modeling", "3D reconstruction",        "Knowledge graphs", "Surface cracks",
        "Scene segmentation", "Depth estimation", "3D reconstruction",
        "Image segmentation", "Image reconstruction", "Image denoising", "Image decomposition", "Image edge detection",
        "Image analysis", "Image segmentation", "Object detection", "Object segmentation", "Scene parsing", "Scattering", 
        "Active contours", "Apertures", "Measurement", "Optical detectors", "Optical losses", 
        "Optical computing", "Optical distortion", "Optical sensors", "Optical surface waves", 
        "Optical variables control", "Optical wavelength conversion", "Refractive index",
        "Surface reconstruction", "Surface morphology", "Surface texture", "Surface treatment", "Surface acoustic waves",
        "Skeleton", "Surface waves", "3D reconstruction",
        "Bundle adjustment",
        "Depth estimation","Context awareness", "Intelligent systems", "Interactive systems", "Spatial databases",
        "Image fusion",
        "Octrees",
        "Point cloud compression",
        "Scene understanding",
        "Stereo vision", "Image capture",
        "Image enhancement",
        "Inspection", "Optical flow",
        "Superresolution",
        "Three-dimensional printing", "Gabor filters",
        "Machine vision", "Code", "Internet", "Information retrieval", "Search methods",
        "Digital humans", "Indoor environments", "Indoor environment",
    ],
    "Vision for Social Good": [
        "Accessibility", "Wildlife monitoring", "Disaster management", 
        "Social media analysis", "Assistive technology", "Crowdsourcing",
        "Wildlife monitoring", "Disaster management", "Social media analysis",
        "Market research", "Social media analysis", "Location awareness", "Disaster management",
        "Social network services", "Disaster management", "Wildlife monitoring", "Crowdsourcing", "Crowd monitoring", "Accessibility",
        "Assistive technologies", "Voting", "Computer bugs",
        "Education", "Innovations", "Trends",
        "Healthcare", "Media",
        "Smart agriculture",
        "Vision for social good", "Employment",
        "Ergonomics", "Maintenance engineering",
        "Risk management", "Green products",
        "Social factors", "Traffic control",
        "Irrigation", "Light fields", "Optics", "Optical variables measurement",
        "Economics", "Pollution", "Road transportation", "Telecommunication traffic", "Working environment noise", 
        "Finance", "Fires", "Government", "Grasping", 
        "Green energy", "Greenhouses", "Recycling", 
        "Road safety",  "Disasters",  "History", "Anisotropic",
        "Psychology", "History",
        "Developing countries", "Customer relationship management",
        "Urban planning", "Road accidents", 
        "US Department of Homeland Security",
        "Sociology", "Economic indicators", 
        "Philosophical considerations",
        "Law", "Archeology", "Communication cables", "Architecture",
    ],    
    "Datasets and Benchmarks": [
        "Large-scale datasets", "Benchmark testing", "Vision datasets", 
        "Training techniques", "Evaluation protocols", "Dataset creation",
        "Large-scale datasets", "Benchmark testing", "Vision datasets",
        "Image databases", "Indexes", "Indexing", "Training data", "Benchmarks",
        "Data augmentation",
        "Datasets","Demography", "Geography", "Meteorological radar", "Millimeter wave radar", "Mars",
        "Evaluation metrics",
        "Ground truth","Big Data applications", "Reviews", "Surveys",
        "Performance evaluation",
        "Reproducibility of results", "NIST", "Annotations", "Measurement units",
        "Throughput", "Crops", "Data structures", "Databases", "Knowledge acquisition", 
    ],
    "Tools and Frameworks": [ "Internet of Things", "Actuators", "Instruments", 
        "Toolkits", "OpenCV", "Software tools", "Hardware tools", 
        "Development frameworks", "Programming libraries",
        "Software tools", "Hardware", 
        "Adaptive optics",  "Memory management", "Memory modules", "Network architecture", "Network topology", 
        "Next generation networking", "Neural networks", "Neurons", "Microprocessors", 
        "Minimization methods", "Parallel processing", "Peer-to-peer computing", "Routing", "Registers", "Real-time systems",
        "Software", "Servers", "Runtime", "Stacking",  "Tools", "Web services", "APIs",
        "Frameworks",
        "Libraries",
        "Machine learning algorithms","Additive noise", "Array signal processing", "Beam steering", "Low-pass filters", "Multiple signal classification", 
        "Partitioning algorithms", "Source coding", "System-on-chip",
        "Programming tools",
        "Software development management",
        "Toolkits", "Printers","Conditional random fields", "Filters", "Logic programming", "Markov decision processes", "Metasearch", 
        "Nearest neighbor methods", "Noise", "YOLO",
        "Portable document format",
        "Tutorials", "Simulation",
        "Numerical simulation", "Deep learning",
        "Evolutionary computation",
        "Control systems",
        "Computational neuroscience",
        "Timing", "Band-pass filters", "Fast Fourier transforms", "Entropy coding", "Phase estimation", "Maximum a posteriori estimation", 
        "Mean square error methods", "Frequency synthesizers", "Neural circuits", "Neural implants", "Soft sensors", "Transformer cores", 
        "Synthesizers", "Sensors systems and applications", "X3D"
    ],
    "Data Collection and Management": [ "Inventory management",
        "Data collection", "Data mining", "Data models", 
        "Data acquisition", "Metadata", "Annotation tools",
        "Data collection", "Data mining", "Data models", "Data acquisition", "Metadata", "Annotation tools",
        "Data models", "Data acquisition", "Metadata", "Annotation tools",
        "Merging", "Probes", "Random access memory", "Random variables",
         "Sampling methods", "Sorting", "Tagging", "Testing", "Task analysis", "Training", "Big Data",
        "Data collection",
        "Data privacy",
        "Data protection","Embedded systems", "Sensor phenomena and characterization", "Volume measurement", "Wavelength measurement",
        "Data-driven modeling",
        "Distributed databases","Data compression", "Data preprocessing", "Debugging", "Energy conservation", "Load modeling", 
        "Power supplies", "Production systems", "Programming", "Random processes", "Recycling", "Systems modeling",
        "Storage management", "Data assimilation",
        "Resource management", "Data transfer",
        "Decontamination",
        "Cleaning", "Channel estimation", "Data visualization",
        "Information processing", 
        "Data processing", 
        "Current measurement", "Position measurement", "Measurement uncertainty", "Power grids", "Power system stability", "Power industry", "Sensor systems"
    ],
    "Core Vision Algorithms": [ "Fitting", "Human intelligence", "Codes",
        "Anisotropic magnetoresistance","Differential privacy", "Phase measurement", "Surface fitting",
        "Feature extraction", "Image processing", "Convolution", 
        "Convolutional neural networks", "Computational modeling", 
        "Clustering algorithms", "Semantic segmentation",
        "Frequency-domain analysis", "Image color analysis", "Image matching", "Frequency division multiplexing",
        "Pattern matching", "Image edge detection", "Image registration", "Reconstruction algorithms",
        "Adaptive systems", "Bayes methods", "Backpropagation", "Convolutional codes",
        "Frequency selective surfaces", "Image annotation", "Image coding", "Imaging", "Iterative closest point algorithm", 
        "Iterative methods", "Kernel", "Level set", "Inference algorithms", "Markov processes", "Markov random fields", "Mixture models"
        "Prediction algorithms", "Predictive models", "Quantization (signal)", "Rate distortion theory", "Rate-distortion",
        "Support vector machines", "Self-organizing feature maps",
        "Transform coding", "Transforms", "Viterbi algorithm", "Recurrent neural networks", "Classification algorithms",
        "Feature detection",
        "Filtering algorithms",
        "Image classification",
        "Object detection",
        "Segmentation",
        "Tracking", "Thresholding (Imaging)",
        "Iterative algorithms",
        "Matching pursuit algorithms",
        "Multiresolution analysis", "Matched filters",
        "Residual neural networks",
        "Reinforcement learning",
        "Transfer learning", "Sensor fusion",
        "Deep learning",
        "Fuzzy logic",
        "Gabor filters","Frequency estimation", "Frequency measurement", "Gradient methods", "Optical character recognition", "Symbols",
        "Optical buffering",
        "Optical switches", "Deep architecture", "Graph neural networks", "Neural network compression"
        
    ],
    "Mathematical Foundations": ["Hilbert space", "Maximum a posteriori estimation", "Measurement uncertainty", 
        "Optimization techniques", "Closed-form solutions", 
        "Deconvolution", "Decorrelation", "Distance measurement", 
        "Approximation algorithms", "Computational complexity", 
        "Covariance matrices", "Algebra", "Shortest path problem",
        "Optimization techniques", "Closed-form solutions", "Approximation algorithms", "Computational complexity", "Covariance matrices",
        "Covariance matrices", "Entropy", "Estimation", "Extrapolation", "Euclidean distance", "Laplace equations", 
        "Maximum likelihood estimation", "Matrix decomposition", "Linear approximation", "Linear systems", 
        "Linear programming", "Linear matrix inequalities", "Monte Carlo methods",
        "Optimization methods", "Quadratic programming", "Parametric statistics", "Probability", "Probability density function", 
        "Probability distribution", "Principal component analysis", "Inverse problems", "Perturbation methods", "Optimization",
        "Acceleration", "Adaptation models", "Channel capacity", "Chebyshev approximation",
        "Graph theory", "Graphical models", "Geometry", "Jacobian matrices", 
        "Mathematical model", "Method of moments", "Minimization",
        "Manifolds", "Numerical models", "Probabilistic logic", "Quaternions", "Random variables", "Differential equations",
        "Finite element analysis", "Radon", "Sparse matrices", "Stochastic processes", "Semisupervised learning", "Semantics",
        "Symmetric matrices", "Transfer functions", "Tree graphs", "Upper bound", "Calculus",
        "Linear algebra",
        "Optimization",
        "Probability theory",
        "Statistics",
        "Tensors",
        "Vector quantization", "Parameter estimation",
        "Optimal matching",
        "Estimation error",
        "Angular velocity",
        "Time-domain analysis", "Correlation coefficient",
        "Linear regression",
        "Linearity","Diffusion processes", "Directed graphs", "Mathematical models", "Sensitivity analysis",
        "Ordinary differential equations",
        "Stability analysis", "Nash equilibrium",
        "Limiting",
        "Performance gain", "Nash equilibrium",
        "Limiting",
        "Performance gain", "Complex networks", "Heterogeneous networks", "Diversity methods", "Fractals", "Entropy coding",
        "Eigenvalues and eigenfunctions", 
        "Convergence", "Convex functions", "Analytical models", "Complexity theory", "Cost function",
        "Harmonic analysis", "Hamming distance", "Heuristic algorithms", "Bipartite graph",
        "Dimensionality reduction", "Discrete cosine transforms", "Dispersion", "Distortion", "Distribution functions", 
        "Transmission line matrix methods", "Time factors", "Time measurement", "Topology", 
        "Splines (mathematics)", 
        "Uncertainty", "Boundary conditions", "Cause effect analysis",
        "Thesauri",
        "Vectors",
    ],
    "Signal and Statistical Processing": ["Friction",
        "Laser beams",  "Fluctuations", "Frequency estimation", "Frequency measurement", "Low-pass filters", "Optical noise",
        "Correlation", "Covariance matrices", "Noise reduction", 
        "Bayesian methods", "Statistical models","AWGN", "Noise", "Random processes",
        "Correlation", "Covariance matrices", "Noise reduction", "Bayesian methods", "Statistical models",
        "Bayesian methods", "Noise reduction", "Statistical models", "Gaussian distribution", "Gaussian mixture model", 
        "Gaussian noise", "Gaussian processes", "Kalman filters", "Hidden Markov models", "Filtering", "Frequency modulation",
        "Noise measurement", "Noise robustness", "Signal resolution", "Signal to noise ratio", "Mutual information", 
        "Gaussian distribution", "Gaussian noise", "Bayesian methods", "Statistical models", "Kalman filters", 
        "Hidden Markov models", "Frequency modulation", "Gaussian mixture model",
        "Absorption", "Acceleration", "Attenuation", "Bandwidth", "Bit error rate", "Bit rate",
        "Histograms", "Interference", "Interpolation",
        "Loss measurement", "Nonlinear distortion", "Nonlinear optics", "Modulation",
        "Optimized production technology", "Power demand", "Potential energy", "Redundancy",
        "RF signals", "Radio frequency", "Spectral analysis", "Spectrogram", "Sensitivity", "Smoothing methods",
        "Source separation", "Wavelet domain", "Wavelet transforms", "Discrete wavelet transforms",
        "Fourier series",
        "Image filtering",
        "Signal processing algorithms",
        "Statistical analysis",
        "Time series analysis",
        "Time-frequency analysis", "Transmission line measurements",
        "Magnetic losses",
        "Magnetic separation", "Compressed sensing",
        "Diversity reception",
        "Spread spectrum communication", "Channel estimation",
        "Current measurement",
        "Splicing", "Channel estimation",
        "Current measurement",
        "Splicing", "Band-pass filters", "Fast Fourier transforms", "Entropy coding", "Transportation"
    ],
    "Industrial and Manufacturing Applications": ["Tungsten",
        "Quality control", "Factory automation", "Defect detection", 
        "Assembly line monitoring", "Industrial vision", "Batch production systems", 
        "Buildings", "Architecture", "Bridges",
        "Quality control", "Factory automation", "Defect detection", "Industrial vision", "Batch production systems"   ,
        "Flyback transformers", "Micromechanical devices", "Laser modes", "Laser radar", "Lasers", "Integrated circuits", 
        "Integrated optics", "Geometrical optics", "Electronics packaging",
        "Quality assessment", "Quality control", "Factory automation", "Defect detection", "Industrial vision", 
        "Batch production systems", "Particle measurements", "Particle separators", "Printing", "Micromechanical devices", 
        "Laser radar", "Flyback transformers", "Integrated circuits", "Laser modes", "Laser radar", "Resists", 
        "Geometrical optics", "Integrated optics", "Electronics packaging", "Geophysical measurement techniques",
        "Additives", "Aggregates", "Generators", "Industries", "Lenses", "Manganese", "Mirrors",  "Ovens", "Periodic structures", "Photonics",
        "Proposals", "Prototypes", "Surface cleaning", "Switched mode power supplies", "Silicon", "Silicon carbide",
        "Toy manufacturing industry", "Technological innovation", "Variable speed drives", "Tires", "Aerospace electronics",
        
        "Fasteners","Casting", "Concrete", "Motors", "Power capacitors", "Resistance",
        "Filling",
        "Pressing",
        "Production",
        "Refining",
        "Three-dimensional printing",
        "Integrated circuits",
        "Optical detectors",
        "Pipelines",
        "Switches", "3D printing",
        "Automation",
        "Industrial inspection",
        "Manufacturing processes",
        "Process control",
        "Quality assurance",
        "Robotic arms", "Integrated circuit modeling",
        "Light emitting diodes",
        "Magnetic heads",
        "Printers",
        "Mixers", "Biomedical equipment", "Materials reliability", "Semiconductor device modeling", "Pumps", "Radar antennas",
        "Meters",
        "Vegetable oils",
        "Vents", "Catalysts","Metasurfaces", "Sensor phenomena and characterization",
        "Product design",
        "Traffic control", "CMOS image sensors", "Electronic commerce", "Energy consumption", "Power line communications", "Power system stability", 
        "Microwave integrated circuits", "Organic light emitting diodes", "Transformer cores", "Transformers", "Space missions"
    ],
    "Ethics and Fairness in Vision": [
        "Fairness in AI", "Bias in datasets", "Ethical AI", "Social networking (online)",
        "Privacy in vision systems", "Explainable AI",
        "Intellectual property", "Bias detection",
        "Guidelines",
        "Uncertainty", "Bias mitigation",
        "Ethics",
        "Fairness", "Philosophical considerations",
        "Privacy concerns",
        "Regulation","Risk minimization",
        "Transparency","Humanities",
        "Trustworthiness", "Collaborative work", "Diversity methods", "Ethical considerations in design"       
    ],
    "Miscellaneous": [
        "Asia", "Australia", "Europe", "Facebook", "Flickr", "Google", "Microsoft Windows",  "Fans", 
        "Feeds", "Feedback loop", "Games",
        "Coherence", "Collaboration", 
        "Computer architecture", "Computer science", "Computer vision", "Computers", "Containers", 
        "Best practices",
        "Cascading style sheets", 
        "Encyclopedias",
        "Facsimile", "Focusing", 
        "Forecasting",
        "ISO",  
        "Logistics", "Logic gates",  "Machine learning",
        "Standards", "Standardization", "Scalability", "Schedules", "Search problems", "Shape", 
        "Smart phones", 
        "Unsupervised learning", "Visualization", "Watermarking" , "Windows", "Wireless communication", "YouTube", 
        "Games", "Corporate acquisitions", 
        "Current transformers",  "Documentation", 
        "Insects", "Licenses", 
        "Metalearning", 
        "Nuclear measurements", "Nuclear power generation", 
        "Ontologies", "PROM", "Pairwise error probability",
        "Power measurement", "Protection", "Publishing", "Purification", 
        "Shape measurement", "Size measurement", "Space mapping", "Sparse approximation", "Stability criteria", 
        "Stars", "Streams", "Supply chains", "Watches", "Web sites",
        "Metasearch", "Multispectral imaging", "Plugs", "Production systems", "Productivity", "Program processors", 
        "Programming", "Rigidity", "Spatial audio", "Steganography", "Sun", 
        "Deformation",  "Artificial intelligence",
        "Miscellaneous topics", "Open challenges",
        "Rhythm", "Conferences", "IEEE Constitution",
        "Vehicular ad hoc networks", "Two-dimensional displays", "Organizations",
        "Multimedia Web sites", "Reliability engineering",
        "Reliability theory", "Length measurement",  "Phase change materials", 
        "Ash", "Business", "Companies", "Costs", "Customer satisfaction", "Design methodology",
        "Electronic commerce", "Fault tolerant systems",  "Glands", "Headphones",  "Lead", 
        "Microwave integrated circuits", "Multitasking", "Neural circuits",
        "Observers", "Orifices", "Patents", "Performance analysis", "Phase estimation", "Position measurement", 
        "Power grids", "Reflection", "Reverse engineering",
        "Solution design", "Speckle",  "Surges", "Telescopes", "Thermal sensors", 
        "Turning", "Valves", "Fats", "High frequency", "Appraisal", "Certification", "Closed box", "Comets", 
        "Commonsense reasoning", "Computer network reliability", "Costing", 
        "Ensemble learning",  "Observability", "Optical pumping", 
        "Polarization", "Question answering (information retrieval)",  "Reflectivity", 
        "Research and development", "Stimulated emission", "Symbiosis", "Tail", 
        "Termination of employment", "Torque", "Ultraviolet sources", "Uniform resource locators", "Web pages"
    ]
}

def process_csv(file_path):
    # Dictionaries to store counts
    grouped_counts = defaultdict(lambda: {"total": 0, "company": 0, "university": 0})

    with open(file_path, 'r', encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            # Check if "ieee_keywords" section is empty
            if not row.get('ieee_keywords'):
                continue
            
            if row['company_affiliation'] == '':  # Skip rows with missing company affiliation
                company_affiliation = 0
            else:
                company_affiliation = float(row['company_affiliation'])

            

            # Determine if the paper is company or university
            is_company = company_affiliation > 0

            # Extract keywords from the "ieee_keywords" column
            keywords = ast.literal_eval(row['ieee_keywords'])  # Convert string list to actual list

            for keyword in keywords:
                for group, group_keywords in keyword_groups.items():
                    if keyword in group_keywords:
                        grouped_counts[group]["total"] += 1
                        if is_company:
                            grouped_counts[group]["company"] += 1
                        else:
                            grouped_counts[group]["university"] += 1

    return grouped_counts

def write_results_to_file(keyword_counts, output_file):
    with open(output_file, 'w', encoding="utf-8") as f:
        f.write(f"{'Keyword':<30} {'Total Papers':<15} {'Company Papers':<15} {'University Papers':<15}\n")
        f.write("-" * 75 + "\n")
        for keyword, counts in sorted(keyword_counts.items(), key=lambda x: x[0]):
            f.write(f"{keyword:<30} {counts['total']:<15} {counts['company']:<15} {counts['university']:<15}\n")
            
def extract_unique_keywords(file_path, output_file):
     # Flatten the keyword_groups dictionary into a set of grouped keywords
    grouped_keywords = set(keyword for group in keyword_groups.values() for keyword in group)
    
    unmatched_keywords = set()  # Use a set to store unique unmatched keywords

    with open(file_path, 'r', encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            # Check if "ieee_keywords" section is empty
            if not row.get('ieee_keywords'):
                continue

            # Extract keywords as a list
            try:
                keywords = ast.literal_eval(row['ieee_keywords'])  # Convert string list to actual list
                for keyword in keywords:
                    if keyword not in grouped_keywords:
                        unmatched_keywords.add(keyword)  # Add unmatched keywords to the set
            except (ValueError, SyntaxError):
                # Skip rows with invalid keyword formatting
                continue

    # Write unmatched keywords to the output file
    with open(output_file, 'w', encoding="utf-8") as outfile:
        for keyword in sorted(unmatched_keywords):  # Sort keywords alphabetically
            outfile.write(keyword + '\n')

# Replace 'your_file.csv' with the path to your CSV file
file_path = '/Users/irem/Desktop/Data_Literacy_Project/Data_Literacy/data/cvpr_preprocessed/cvpr2019.csv'
output_file = '/Users/irem/Desktop/Data_Literacy_Project/Data_Literacy/data/cvpr_preprocessed/results_19.txt'
keyword_file = '/Users/irem/Desktop/Data_Literacy_Project/Data_Literacy/data/cvpr_preprocessed/keywords_19.txt'
extract_unique_keywords(file_path, keyword_file)
keyword_counts = process_csv(file_path)
write_results_to_file(keyword_counts, output_file)
